/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f407xx.h"

SPI_HandleTypedef_t SPI_Handle;

void GPIO_Config();
void EXTI_Config();
void EXTI0_IRQHandler()
{

	if(EXTI->PR & 0x1)
	{
		EXTI->PR = 0x1;
		GPIO_TogglePin(GPIOD, GPIO_PIN_12 | GPIO_PIN_13 | GPIO_PIN_14 | GPIO_PIN_15);
	}

}

int main(void)
{
    /* Loop forever */


	GPIO_Config();

	EXTI_Config();





	for(;;);

}
void GPIO_Config()
{
	RCC_GPIOD_CLOCK_ENABLE();
	RCC_GPIOA_CLOCK_ENABLE();
	GPIO_InitTypeDef_t GPIO_InitStruct = { 0 };
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT;
	GPIO_InitStruct.pinNumber = GPIO_PIN_12 | GPIO_PIN_13 | GPIO_PIN_14 | GPIO_PIN_15;
	GPIO_InitStruct.Otype = GPIO_OTYPE_PP;
	GPIO_InitStruct.PuPd = GPIO_PUPD_NOPULL;
	GPIO_InitStruct.Speed = GPIO_OSPEED_HIGH;

	GPIO_Init(GPIOD, &GPIO_InitStruct);


}
void EXTI_Config()
{
	RCC_SYSCFG_CLOCK_ENABLE();
	EXTI_LineConfig(EXTI_PortSource_A,EXTI_LineSource_0);

	EXTI_InitTypeDef_t EXTI_InitStruct={0};

	EXTI_InitStruct.LineCmd = ENABLE;
	EXTI_InitStruct.LineNumber = EXTI_LineSource_0;
	EXTI_InitStruct.Mode = EXTI_MODE_IMR;
	EXTI_InitStruct.TriggerSelection = EXTI_Trigger_Rising;


	EXTI_Init(&EXTI_InitStruct);
	NVIC_InterruptEnable(EXTI0_IRQNumber);

}

